language: node_js
services:
  - mysql
  - memcached
node_js:
  - '0.10'
before_script:
  - mysql -e 'create database aiveo;'
deploy:
  provider: heroku
  app: aiveo
  on: master
  api_key:
    secure: BFmVlKiiGesN70XqxMt+G3v7W6BnXcKRNyNWaQv/656sKTGj0M/iLAwlBQhI/KRTUaDAkQQyfDTp9722pj2ChRH6q/UZzJmDY0XuUIT5Pz7BwluYNFRArAQ88b3CqhX/aSKEXue5OgItH4QXri9iojDvNcNaMY4wrnWsSLnt7Js=
